### ISSUE TITLE
dependency on non-existent package rqt_cpp_common

### ISSUE THREAD

**Issue by tfoote** [rosjava/rosjava_messages#9]
This appears to have been scraped into the dependencies. All the other regressions have been fixed. I'd like to sync hydro when this is fixed.

**Comment by dirk-thomas** [comment]
It looks like this has already been fixed in 0.1.58 but the latest released version currently is 0.1.56.

**Comment by stonier** [comment]
https://github.com/ros/rosdistro/pull/2896

Wondering if there's a better way to do this so you don't have to go chasing...nor chasing the details.

Perhaps a message on the release mailing list that you plan to sync at the end of the week? I can make sure all our packages are working over the course of the week. This is important in this situation, but also in others as we can't often tell till a dependency is repaired (eg openni-camera this week). Catching this on an american friday usually finds me not so contactable being the weekend already here.

**Comment by dirk-thomas** [comment]
The buildfarm is already sending notification emails to the maintainer(s). Some times it happens that you can't address the package in a package itself since some upstream package is responsible for the failure. But otherwise a failing build should get the attention of the maintainer. I am not sure if more emails would help at all. There should always be the attempt to have stuff building without failures (or even warnings) - not only when a sync is about to happen.

**Comment by stonier** [comment]
That's ok. It's actually not an issue on my end at all. The notifications as they are right now are not a problem. 

I suggested an advance email to help with planning. I'm sure you all understand that being incredibly busy means that some (most) things can't be addressed immediately as soon as you receive a notification. Or immediately when some pre-condition is satisfied. And occasionally too, a notification will slip under the radar.

Tully already posts late in the process that he's got everything building and is planning a release on a Monday. An email a bit earlier would let us be able to prioritise our plans to make sure you can hit your release plan as well. I can't always help you very easily via a notification on a Saturday morning.

**Comment by tfoote** [comment]
@stonier The email shortly before release is not so much a call for new releases but a request not to make releases, and to tell me if there are known regressions not indicated on the build farm. In the past there have been known regressions that I have synced because they built but failed at runtime. However no one opened a ticket or emailed me about the regression. 

I'll think about doing two emails. One calling for releases and one calling for any blockers.
